---
- name: Install python2
  raw: yum -y install python2
  become: True
  register: yum
  changed_when: "'Nothing to do' not in yum.stdout"

- name: Set Ansible Python Interpreter
  set_fact:
    ansible_python_interpreter: /usr/bin/python2.7

- name: Install requirements for Ansible Modules
  yum:
    name: "{{ package }}"
  become: True
  with_items:
    - python-firewall
    - libselinux-python
    - policycoreutils-python
  loop_control:
    loop_var: package
